dir: "/homes/hannah/data/digital-heart/gwas/FD"
imputedir: "/homes/hannah/data/digital-heart/genotype/imputation/combined"
genodir: "/homes/hannah/data/digital-heart/genotype/QC/combined"
phenodir: "/homes/hannah/data/digital-heart/phenotype"
name: "gencall.combined.clean.related"
n : "8"
interpolate: "9"
ukbdir: "/homes/hannah/data/ukbb/ukb-hrt/gwas/180628_fractal_dimension"
discovery: "180628_fractal_dimension"
qcdir: "/homes/hannah/data/digital-heart/genotype/QC/combined"
plink: "/homes/hannah/bin/plink"
