dir: "/homes/hannah/data/digital-heart/association"
imputedir: "/homes/hannah/data/digital-heart/genotype/imputation/combined"
genodir: "/homes/hannah/data/digital-heart/genotype/QC/combined"
sigdir: "/homes/hannah/data/ukbb/ukb-hrt/gwas"
name: "gencall.combined.clean.related"
n : "8"
