gwasdir: "/homes/hannah/data/digital-heart/gwas/FD"
genodir: "/homes/hannah/data/digital-heart/genotype/imputation/combined"
phenodir: "/homes/hannah/data/digital-heart/phenotype/FD"
name: "gencall.combined.clean.related"
n : "8"
ukbdir: "/homes/hannah/data/ukbb/ukb-hrt/gwas/180628_fractal_dimension"
qcdir: "/homes/hannah/data/digital-heart/genotype/QC/combined"
