
qcdir : "/homes/hannah/data/genotype/QC"
dir : "/homes/hannah/data/genotype/imputation/combined"

threads : 8
window : 2
states : 200
map : "/homes/hannah/data/hmeyer/UK10K1000Genomes/genetic_map_chr{}_combined_b37.txt"

buffer_size : 250
k_hap : 1000
Ne : 20000
referencedir : "/homes/hannah/data/hmeyer/UK10K1000Genomes"

infoTh : 0.4
missingTh : 0.01
hweTh : "1e-5"
mafTh : 0.005
